### ISSUE TITLE
How do you register a SubscriptionManager?

### ISSUE THREAD

**Issue by lawrences-racti** [Shuttle/Shuttle.Esb.Sql.Subscription#2]
Hi Eben

We don't seem to get our subscription manager automatically registered.
Is there a way to register the default Shuttle.Esb.Sql.Subscription version?
Should we be registering this using the container config (https://github.com/Shuttle/Shuttle.Core.Container)?

Is there a way to force loading of a IComponentRegistryBootstrap class in a DLL?

**Comment by eben-roux** [comment]
If you call something that initiates the component bootstrapping, like `ServiceBus.Register(registry);`, then the `SubscriptionManager` in the `Shuttle.Esb.Sql.Subscription` assembly really should be registered.

The [pub/sub sample](https://github.com/Shuttle/Shuttle.Esb.Samples/tree/master/Shuttle.PublishSubscribe) does this.

Can you perhaps send me a sample application?

**Comment by lawrences-racti** [comment]
Hi Eben

It could take me a while to scratch out a sample. I have looked at the samples and the only material difference is that we are changing the connectionStringName in the SubscriptionSection and not using the default ("Subscription").

I had a look at the code and I cannot see how the Subscription Bootstrap code is called. We seem to be gettting the NullSubscriptionManager registered.

If I instantiate the SubscriptionManager bootstrap code explicitly it seems to work.
`
   ServiceBus.Register(registry);
   var bootstrap = new Shuttle.Esb.Sql.Subscription.Bootstrap();
   bootstrap.Register(registry);
`   

Thanks

**Comment by eben-roux** [comment]
That seems quite odd.

The `ServiceBus.Register` method will kick off the bootstrapping:

![image](https://user-images.githubusercontent.com/5379436/38658329-fa8be5ec-3e24-11e8-9f7e-a1010c7e3119.png)

This ends up in the [RegistryBootstrap](https://github.com/Shuttle/Shuttle.Core.Container/blob/70d1050b21be33b77262d0105154ee8c00d1e30e/Shuttle.Core.Container/Registry/ComponentRegistryExtensions.cs#L315) method where all the types implementing the [IComponentRegistry](https://github.com/Shuttle/Shuttle.Core.Container/blob/master/Shuttle.Core.Container/Registry/IComponentRegistryBootstrap.cs) interface are instantiated and invoked.

The `Shuttle.Esb.Sql.Subscription` assembly has this implemented in the [Bootstrap](https://github.com/Shuttle/Shuttle.Esb.Sql.Subscription/blob/master/Shuttle.Esb.Sql.Subscription/Bootstrap.cs) class.

Some ideas may be to ensure that the `Shuttle.Esb.Sql.Subscription` assembly is referenced and exists in the output/deployment folder.  Perhaps add a `Console.WriteLine(registry.IsRegistered<ISubscriptionManager>());` just after the registration and check that whether it is registered.

Which DI container are you using?

**Comment by eben-roux** [comment]
Did you manage to get this sorted at all?
